name: Ubuntu 20.04 Makefile

on:
  push:
    branches: [ OpenMPT-1.30 ]
  pull_request:
    branches: [ OpenMPT-1.30 ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y subversion libxml-xpath-perl git mawk zip unzip p7zip xz-utils make binutils gcc g++ clang tcc pkg-config help2man doxygen autoconf autoconf-archive automake libtool ccache zlib1g-dev libmpg123-dev libogg-dev libvorbis-dev portaudio19-dev libpulse-dev libsdl2-dev libflac-dev libsndfile1-dev libltdl-dev
    - name: make
      run: make STRICT=1
    - name: make check
      run: make STRICT=1 check
