task:
    name: freebsd-13-0
    freebsd_instance:
        image_family: freebsd-13-0
    install_script: pkg install -y subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2
    build_script: gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 clean && gmake STRICT=1 VERBOSE=1 AUTO_DEPS=1
    test_script: gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 AUTO_DEPS=1 check

task:
    name: freebsd-13-0-minimal
    freebsd_instance:
        image_family: freebsd-13-0
    install_script: pkg install -y subversion p5-XML-XPath git mawk gmake pkgconf autoconf autoconf-archive automake libtool help2man doxygen mpg123 libogg libvorbis flac libsndfile pulseaudio portaudio sdl2
    build_script: gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 FORCE_DEPS=1 CONFIG= NO_ZLIB=1 NO_MPG123=1 NO_OGG=1 NO_VORBIS=1 NO_VORBISFILE=1 NO_STBVORBIS=0 NO_MINIMP3=0 NO_PORTAUDIO=1 NO_PORTAUDIOCPP=1 OPENMPT123=1 NO_PULSEAUDIO=1 NO_SDL2=1 NO_SNDFILE=1 NO_FLAC=1 clean && gmake STRICT=1 VERBOSE=1 FORCE_DEPS=1 CONFIG= NO_ZLIB=1 NO_MPG123=1 NO_OGG=1 NO_VORBIS=1 NO_VORBISFILE=1 NO_STBVORBIS=0 NO_MINIMP3=0 NO_PORTAUDIO=1 NO_PORTAUDIOCPP=1 OPENMPT123=1 NO_PULSEAUDIO=1 NO_SDL2=1 NO_SNDFILE=1 NO_FLAC=1
    test_script: gmake -j$(sysctl -n hw.ncpu) STRICT=1 VERBOSE=1 FORCE_DEPS=1 CONFIG= NO_ZLIB=1 NO_MPG123=1 NO_OGG=1 NO_VORBIS=1 NO_VORBISFILE=1 NO_STBVORBIS=0 NO_MINIMP3=0 NO_PORTAUDIO=1 NO_PORTAUDIOCPP=1 OPENMPT123=1 NO_PULSEAUDIO=1 NO_SDL2=1 NO_SNDFILE=1 NO_FLAC=1 check

task:
    name: macos-xcode14
    macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:14
    install_script: brew update && brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile
    build_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1
    test_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1 check

task:
    name: macos-xcode13
    macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:13.4.1
    install_script: brew update && brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile
    build_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1
    test_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1 check

task:
    name: macos-xcode12
    macos_instance:
        image: big-sur-xcode-12.5
    install_script: brew update && brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile
    build_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1
    test_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1 check

task:
    name: macos-xcode11
    macos_instance:
        image: catalina-xcode-11.6
    install_script: brew update && brew install p7zip help2man doxygen autoconf-archive mpg123 libogg libvorbis portaudio flac libsndfile
    build_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1
    test_script: make -j$(sysctl -n hw.ncpu) STRICT=1 FORCE_DEPS=1 NO_SDL2=1 check
